services:
  - type: web
    name: hanza-bot
    env: node
    plan: free
    region: oregon

    buildCommand: "npm ci"               # or: npm ci && npm run build:index
    startCommand: "npm start"
    autoDeploy: true
    healthCheckPath: /health

    # Persist /data (index, transcripts, PDFs) across deploys
    disk:
      name: hanza-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

    envVars:
      # Runtime config
      - key: NODE_VERSION
        value: 20
      - key: OPENAI_MODEL
        value: gpt-5-nano
      - key: OPENAI_EMBED_MODEL
        value: text-embedding-3-small
      - key: DEMO_MODE
        value: "false"

      # Provide your API key via the dashboard (kept out of git)
      - key: OPENAI_API_KEY
        sync: false    # set the value in Render's dashboard after first deploy
